### ISSUE TITLE
`ModeMatchers::equalsDeeply` fails to identity equality if elements contain references

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv-Change#53]
Apparently, the `ModelMatchers` of the `testutils` fails to identify elements as equal if they contain some references. This issue first appeared when refactoring the Java <-> PCM tests and comparing some Java elements here. 

> There is a problem with assertion of the java models (actual vs. expected), which didn't occur on my windows setup. "equalsDeeply" fails if references are used in the model.
If you ignore the feature target (pointer of the reference object) all tests run. Todo this replace line 147 in Pcm2JavaTransformationTest.xtend with `assertThat(actualUnit, equalsDeeply(it, ignoringFeatures("target")))`
>
> All failed tests follow the same scheme. One example for this is the AssemblyContextMappingTransformationTest. This test produces the following diff/output:

<details>
<summary>AssemblyContextMappingTransformationTest</summary>

```
java.lang.AssertionError: 
Expected: a CompilationUnit deeply equal to <CompilationUnit#1(
        name="testSystem.TestSystemImpl.java"
        namespaces=["testSystem"]
        layoutInformations=[]
        imports=[ClassifierImport#1(
                namespaces=[
                        "testRepository",
                        "TestBasicComponent"
                ]
                layoutInformations=[]
                classifier=Class#1
        )]
        classifiers=[Class#2(
                name="TestSystemImpl"
                layoutInformations=[]
                typeParameters=[]
                members=[
                        Constructor#1(
                                name="TestSystemImpl"
                                layoutInformations=[]
                                statements=[ExpressionStatement#1(
                                        layoutInformations=[]
                                        expression=AssignmentExpression#1(
                                                layoutInformations=[]
                                                child=SelfReference#1(
                                                        layoutInformations=[]
                                                        typeArguments=[]
                                                        next=IdentifierReference#1(
                                                                layoutInformations=[]
                                                                typeArguments=[]
                                                                next=∅
                                                                arraySelectors=[]
                                                                target=Field#1
                                                        )
                                                        arraySelectors=[]
                                                        self=This#1(layoutInformations=[])
                                                )
                                                assignmentOperator=Assignment#1(layoutInformations=[])
                                                value=NewConstructorCall#1(
                                                        layoutInformations=[]
                                                        typeReference=NamespaceClassifierReference#1(
                                                                namespaces=[
                                                                        "testRepository",
                                                                        "TestBasicComponent"
                                                                ]
                                                                layoutInformations=[]
                                                                classifierReferences=[ClassifierReference#1(
                                                                        layoutInformations=[]
                                                                        typeArguments=[]
                                                                        target=Class#1
                                                                )]
                                                        )
                                                        typeArguments=[]
                                                        next=∅
                                                        arraySelectors=[]
                                                        arguments=[]
                                                        callTypeArguments=[]
                                                        anonymousClass=∅
                                                )
                                        )
                                )]
                                parameters=[]
                                typeParameters=[]
                                exceptions=[]
                                annotationsAndModifiers=[Public#1(layoutInformations=[])]
                        ),
                        Field#1(
                                name="assemblyContext"
                                layoutInformations=[]
                                initialValue=∅
                                typeReference=NamespaceClassifierReference#2(
                                        namespaces=[
                                                "testRepository",
                                                "TestBasicComponent"
                                        ]
                                        layoutInformations=[]
                                        classifierReferences=[ClassifierReference#2(
                                                layoutInformations=[]
                                                typeArguments=[]
                                                target=Class#1
                                        )]
                                )
                                arrayDimensionsBefore=[]
                                arrayDimensionsAfter=[]
                                typeArguments=[]
                                annotationsAndModifiers=[Private#1(layoutInformations=[])]
                                additionalFields=[]
                        )
                ]
                defaultMembers=[]
                annotationsAndModifiers=[Public#2(layoutInformations=[])]
                implements=[]
                extends=∅
                defaultExtends=∅
        )]
)>
     but: found the following differences:
        • .classifiers[0].members[0].statements[0].expression.child (SelfReference#1).next contained the unexpected value: IdentifierReference#2(
                layoutInformations=[]
                typeArguments=[]
                next=∅
                arraySelectors=[]
                target=Field#1
        )
        • .classifiers[0].members[0].statements[0].expression.child (SelfReference#1).next was missing the value: IdentifierReference#1(
                layoutInformations=[]
                typeArguments=[]
                next=∅
                arraySelectors=[]
                target=Field#1
        )
        • .classifiers[0].members[0].statements[0].expression.child.next (IdentifierReference#2).target had the wrong value: Field#1
        • .classifiers[0].members[0].statements[0].expression.child.next.target had the wrong value: Field#1
    for object <CompilationUnit#1(
        name="testSystem.TestSystemImpl.java"
        namespaces=["testSystem"]
        layoutInformations=[]
        imports=[ClassifierImport#1(
                namespaces=[
                        "testRepository",
                        "TestBasicComponent"
                ]
                layoutInformations=[]
                classifier=Class#3
        )]
        classifiers=[Class#2(
                name="TestSystemImpl"
                layoutInformations=[]
                typeParameters=[]
                members=[
                        Constructor#1(
                                name="TestSystemImpl"
                                layoutInformations=[]
                                statements=[ExpressionStatement#1(
                                        layoutInformations=[]
                                        expression=AssignmentExpression#1(
                                                layoutInformations=[]
                                                child=SelfReference#1(
                                                        layoutInformations=[]
                                                        typeArguments=[]
                                                        next=IdentifierReference#2(
                                                                layoutInformations=[]
                                                                typeArguments=[]
                                                                next=∅
                                                                arraySelectors=[]
                                                                target=Field#1
                                                        )
                                                        arraySelectors=[]
                                                        self=This#1(layoutInformations=[])
                                                )
                                                assignmentOperator=Assignment#1(layoutInformations=[])
                                                value=NewConstructorCall#1(
                                                        layoutInformations=[]
                                                        typeReference=NamespaceClassifierReference#1(
                                                                namespaces=[
                                                                        "testRepository",
                                                                        "TestBasicComponent"
                                                                ]
                                                                layoutInformations=[]
                                                                classifierReferences=[ClassifierReference#1(
                                                                        layoutInformations=[]
                                                                        typeArguments=[]
                                                                        target=Class#3
                                                                )]
                                                        )
                                                        typeArguments=[]
                                                        next=∅
                                                        arraySelectors=[]
                                                        arguments=[]
                                                        callTypeArguments=[]
                                                        anonymousClass=∅
                                                )
                                        )
                                )]
                                parameters=[]
                                typeParameters=[]
                                exceptions=[]
                                annotationsAndModifiers=[Public#1(layoutInformations=[])]
                        ),
                        Field#1(
                                name="assemblyContext"
                                layoutInformations=[]
                                initialValue=∅
                                typeReference=NamespaceClassifierReference#2(
                                        namespaces=[
                                                "testRepository",
                                                "TestBasicComponent"
                                        ]
                                        layoutInformations=[]
                                        classifierReferences=[ClassifierReference#2(
                                                layoutInformations=[]
                                                typeArguments=[]
                                                target=Class#3
                                        )]
                                )
                                arrayDimensionsBefore=[]
                                arrayDimensionsAfter=[]
                                typeArguments=[]
                                annotationsAndModifiers=[Private#1(layoutInformations=[])]
                                additionalFields=[]
                        )
                ]
                defaultMembers=[]
                annotationsAndModifiers=[Public#2(layoutInformations=[])]
                implements=[]
                extends=∅
                defaultExtends=∅
        )]
)>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at tools.vitruv.applications.pcmjava.tests.pcm2java.Pcm2JavaTransformationTest.lambda$10(Pcm2JavaTransformationTest.java:168)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at tools.vitruv.applications.pcmjava.tests.pcm2java.Pcm2JavaTransformationTest.assertCompilationUnits(Pcm2JavaTransformationTest.java:170)
	at tools.vitruv.applications.pcmjava.tests.pcm2java.system.AssemblyContextMappingTransforamtionTest.lambda$4(AssemblyContextMappingTransforamtionTest.java:51)
	at tools.vitruv.testutils.TestViewFactory.validateView(TestViewFactory.java:83)
	at tools.vitruv.applications.pcmjava.tests.pcm2java.Pcm2JavaViewFactory.validateJavaView(Pcm2JavaViewFactory.java:34)
	at tools.vitruv.applications.pcmjava.tests.pcm2java.system.AssemblyContextMappingTransforamtionTest.testCreateAssemblyContext(AssemblyContextMappingTransforamtionTest.java:53)
	[...]
```
</details>

_Originally posted by @h4uges in https://github.com/vitruv-tools/Vitruv-CaseStudies/issues/243#issuecomment-1295047672_

**Comment by TomWerm** [comment]
As discusses in the linked PR, we can use the [EqualityHelper](https://download.eclipse.org/modeling/emf/emf/javadoc/2.9.0/org/eclipse/emf/ecore/util/EcoreUtil.EqualityHelper.html#equals(org.eclipse.emf.ecore.EObject,%20org.eclipse.emf.ecore.EObject)).
